baseURL = "https://docs.mysurvey.solutions/"
languageCode = "en-us"
title = "Survey Solutions | Documentation"
theme = "surveysolutions" 
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = true
googleAnalytics = "UA-129284684-1"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "vs"

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[params]
    description = "Knowledge Base for Survey Solutions CAPI and CAWI platform"
    lastreleasenote = "version-25-04"
    contactformurl = "https://pds.mysurvey.solutions/ContactUs"
    images = ['img/logo.png']

    [params.algolia]
        vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
        params = ["categories", "tags"]

    [params.forum]
        url = "https://forum.mysurvey.solutions"
        title = "User Forum"
        suggestions = "/c/feature-suggestions"

[outputs]
    home = ["HTML", "Algolia"]

[outputFormats]
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[related]
threshold = 90
includeNewer = true
toLower = false