baseURL = "https://support-new2.mysurvey.solutions/"
languageCode = "en-us"
title = "Survey Solutions | Support"
theme = "surveysolutions" 
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Knowledge Base for Survey Solutions CAPI and CAWI platform"
    lastreleasenote = "version-18-06"

    [params.algolia]
        vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
        params = ["categories", "tags"]

    [params.forum]
        url = "https://forum.mysurvey.solutions"
        title = "Latest Forum Topics"
        suggestions = "/c/feature-suggestions"

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[outputFormats]
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[related]
threshold = 90
includeNewer = true
toLower = false