baseURL = "https://support.mysurvey.solutions/"
languageCode = "en-us"
title = "Survey Solutions | Support"
theme = "surveysolutions" 
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[params]
    description = "Knowledge Base for Survey Solutions CAPI and CAWI platform"
    lastreleasenote = "version-19-06"
    contactformurl = "https://mysurvey.solutions/ContactUs"

    [params.algolia]
        vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
        params = ["categories", "tags"]

    [params.forum]
        url = "https://forum.mysurvey.solutions"
        title = "User Forum"
        suggestions = "/c/feature-suggestions"

[outputs]
    home = ["HTML", "Algolia"]

[outputFormats]
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[related]
threshold = 90
includeNewer = true
toLower = false