name: publish-docs

on:
  push:
    branches: [ gh-pages ]
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. Do not cancel in-progress runs.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --minify --cleanDestinationDir

    - name: Set custom domain (CNAME)
      run: echo 'docs.mysurvey.solutions' > ./public/CNAME

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Update search index
      continue-on-error: true
      run: |
        python -m pip install --upgrade 'algoliasearch>=2.0,<3.0'
        python update-search-index.py
      env:
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_APP_ID: "5IDMO489J3"

    - name: Remove non-publishable assets
      run: rm -f ./public/algolia.json

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
