name: publish-gh-pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --minify --cleanDestinationDir --source homepage

    - name: Old portal had Download as windows is case insensitive
      run: cp ./homepage/public/download ./homepage/public/Download
  
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: surveysolutions/mysurvey.solutions 
        deploy_key: ${{ secrets.DEPLOY_PAGES }}
        publish_dir: ./homepage/public
        commit_message: ${{ github.event.head_commit.message }}
        force_orphan: true
        cname: mysurvey.solutions
